---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible role"
      include_role:
        name: "ckaserer.macos"
      vars:
        github_user: "ckaserer"
        github_token: "{{ lookup('env','GITHUB_TOKEN') }}"
        macos_mas_apps: []
...