---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
lint: |
  set -e
  ansible-lint .
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: ansible
